theme: jekyll-theme-midnight
title: Welcome to Chris's homepage for CS-499!
description: Homepage for Computer Science Capstone course.

This page is designed to showcase the work I have completed during my time in the Computer Science program at SNHU. 
There are three different artifacts on display that each show a different part of the skills I have learned in this program.
